### GET request to example server
PUT http://localhost:8080/api/produtos/atualizar/
Content-Type: application/json

{
  "nome": "Cereal Matinal Original Kelloggs Sucrilhos Caixa 690g",
  "descricao": "Ingredientes: Milho, açúcar, malte, sal, ferro reduzido (ferro), colecalciferol (vitamina D), cianocobalamina (vitamina B12), mononitrato de tiamina (vitamina B1), cloridrato de piridoxina (vitamina B6) e ácido fólico.",
  "preco": 34.90,
  "quantidadedeestoque": 30
}
###