### GET request to example server
POST http://localhost:8080/api/produtos/inserir
Content-Type: application/json

{
  "nome": "Hambúrguer Sadia de Carne Bovina 672g",
  "descricao": "Receba em casa Hambúrguer Sadia de Carne Bovina 672g e muitos outros produtos do nosso departamento de Freezer.",
  "preco": 22.12,
  "quantidadedeestoque": 20
}
###