name: Spring Boot CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and Test with Maven
      run: cd API_Rest && mvn -B verify --file pom.xml

    - name: Package application
      run: cd API_Rest && mvn -B package --file pom.xml

    - name: Upload JAR Artifact
      run: cd backend
      uses: actions/upload-artifact@v4
      with:
        name: springboot-app
        path: target/*.jar
